services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres-db:5432/postgres
    depends_on:
      - postgres-db

  ws:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres-db:5432/postgres
    depends_on:
      - postgres-db

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.fe
      args:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres-db:5432/postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres-db:5432/postgres
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
